### ISSUE TITLE
Could not run application

### ISSUE THREAD

**Issue by Qoyyuum** [Shashank18May/Advanced-Clock#1]
I'm running the following Java version:

```
> java -version
java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.351-b10, mixed mode)
```

And I tried, assuming this is correct, the right version and way to run a Java app.

```powershell
> java MyFrame.java
Error: Could not find or load main class MyFrame.java
```

Can you update your README file to include instructions on how to run your app and what version of Java is compatible to run it? @Shashank18May 

I can confirm my Java works fine, especially with a HelloWorld.java file to test run with.

**Comment by Shashank18May** [comment]
So you need to make two new files under a single folder as Main.java & MyFrame.java and then save the code respectively in both files 
It is compatible with JAVA 1.7.5 or more.

**Comment by Qoyyuum** [comment]
I was able to get it to work. You will need to add a few more instructions into your README on how to execute it (without debugger or via an IDE). I'll put in a Pull Request for you to review.

**Comment by Qoyyuum** [comment]
@Shashank18May please review the PR. Thanks.
